name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        BANNED_LABELS: "hold"
        BANNED_LABELS_DESCRIPTION: "PRs on hold cannot be merged"
